.github/workflows/build_feature.yaml
src/main/java/de/muenchen/dave/services/processzaehldaten/ProcessZaehldatenBelastungsplanService.java

Fix for bugfix falsche werte zahlen

Fix pull request

---

.github/workflows/build.yaml
.github/workflows/build_feature.yaml
.github/workflows/release.yaml
.github/workflows/snapshot_build.yaml
.gitignore
Dockerfile
IMAGE_README.md
pom.xml
src/main/java/de/muenchen/dave/controller/ZaehlungController.java
src/main/java/de/muenchen/dave/security/RequestResponseLoggingFilter.java
src/main/java/de/muenchen/dave/security/SecurityContextInformationExtractor.java
src/main/java/de/muenchen/dave/services/processzaehldaten/ProcessZaehldatenBelastungsplanService.java
src/main/resources/application-prod.yml

New workflows for github action

Release-20230509-001

---

.github/workflows/release.yaml

Release-20230516-002

---

.github/workflows/release.yaml

Fix job dependency bug in release workflow

Release-20230516-003

---

.github/workflows/release.yaml

* Fix bug with github relase
* Rename jobs
* Change variable output in workflows to new behavior

Release-20230516-004

---

.github/pull_request_template.md

Added PR template according to Definition Of Done in LS2
**Reference**
Issues #XXX

pr template added

---

pom.xml

POM auf 2.0.0 gehoben
**Reference**
Issues #DAVE-102

Pom auf 2.0.0 gehoben

---

src/main/java/de/muenchen/dave/services/SucheService.java

Bei den Suggestions werden nun auch nur die sichtbaren Messstellen vorgeschlagen

fehler bei den Suggestions gefixt

---

src/main/java/de/muenchen/dave/services/messstelle/HeatmapService.java

Reihenfolge der Heatmapeinträge angepasst

Reihenfolge der Heatmapeintraege angepasst

---

src/main/java/de/muenchen/dave/domain/mapper/detektor/MessstelleMapper.java
src/main/java/de/muenchen/dave/domain/mapper/detektor/MessstelleReceiverMapper.java
src/main/java/de/muenchen/dave/geodateneai/gen/model/MessquerschnittDto.java
src/main/java/de/muenchen/dave/geodateneai/gen/model/MessstelleDto.java
src/main/java/de/muenchen/dave/geodateneai/gen/model/StadtbezirkDto.java
src/test/java/de/muenchen/dave/domain/mapper/MessstelleMapperTests.java
src/test/java/de/muenchen/dave/domain/mapper/MessstelleReceiverMapperTests.java
src/test/java/de/muenchen/dave/services/messstelle/MessstelleReceiverTest.java

Messstelle kann nun verschoben werden.

Koordinaten der Messstelle sind nun bearbeitbar

---

src/main/java/de/muenchen/dave/domain/dtos/laden/messwerte/LadeProcessedMesswerteDTO.java
src/main/java/de/muenchen/dave/services/messstelle/BelastungsplanService.java
src/main/java/de/muenchen/dave/services/messstelle/MesswerteService.java
src/test/java/de/muenchen/dave/services/messstelle/BelastungsplanServiceTest.java

variablen name angepasst
Issues:

variable name angepasst

---

src/main/java/de/muenchen/dave/configuration/SecurityConfiguration.java
src/test/java/de/muenchen/dave/configuration/SecuredWebAppTest.java
src/test/java/de/muenchen/dave/configuration/SecuringWebAppTest.java
src/test/resources/application-test.yml

Restored RefArch Security but allow h2-console
Issues: https://github.com/it-at-m/dave-backend/security/code-scanning/2
~~- [ ] Acceptance criteria are met~~
~~- [ ] Release notes are complemented~~
~~- [ ] Documentation is complemented (operator manual, system specification)~~
~~- [ ] Side branches are deleted~~
~~- [ ] Board is updated~~
~~- [ ] Infrastructure is adjusted~~

h2-console security improved

---

src/main/java/de/muenchen/dave/services/messstelle/GenerateCsvMstService.java

Fix bug. Beschreibung des Wochentags in der csv hat gefehlt

fix bug DAVE-280 CSV Export | Wochentage

---

.github/workflows/build_push_ghcr.yaml

Description
From main aka LS-1
Reference
Issues https://github.com/it-at-m/dave-frontend/issues/136

 add .github/workflows/build_push_ghcr.yaml

---

.gitlab-ci.yml

Added gitlab-ci.yml for internal pipeline.
Issues: 
~~- [ ] Acceptance criteria are met~~
~~- [ ] Build/Test workflow has successfully finished~~
~~- [ ] Release notes are complemented~~
~~- [ ] Documentation is complemented (operator manual, system specification)~~
~~- [ ] Frontend is locally smoke-tested~~
~~- [ ] Side branches are deleted~~
~~- [ ] Board is updated~~
~~- [ ] Infrastructure is adjusted~~

Create .gitlab-ci.yml for internal pipeline

---

src/main/java/de/muenchen/dave/scheduler/ZaehlungStatusUpdater.java

Fixed annotation for scheduler.
~~- [ ] Acceptance criteria are met~~
~~- [ ] Build/Test workflow has successfully finished~~
~~- [ ] Release notes are complemented~~
~~- [ ] Documentation is complemented (operator manual, system specification)~~
~~- [ ] Frontend is locally smoke-tested~~
~~- [ ] Side branches are deleted~~
~~- [ ] Board is updated~~
~~- [ ] Infrastructure is adjusted~~

Fixed annotation for scheduler

---

src/test/java/de/muenchen/dave/services/pdfgenerator/GeneratePdfServiceTest.java

Hotfix for unit-test

---

src/main/java/de/muenchen/dave/services/messstelle/MessstelleReceiver.java

DAVE-301 Hotfix

---

.github/workflows/build.yaml
.github/workflows/build_feature.yaml
.github/workflows/build_push_ghcr.yaml
.github/workflows/release.yaml
.github/workflows/snapshot_build.yaml
pom.xml
src/main/resources/application-local.yml

Hebung Spring Frameworks

---

src/main/java/de/muenchen/dave/configuration/CachingConfiguration.java

Refactor Anpassungen Caching

---

src/main/java/de/muenchen/dave/configuration/CachingConfiguration.java

Add additional property to set openshift namespace fpr hazelcast

Bug Fix Hazelcast Namespace

---

src/main/java/de/muenchen/dave/configuration/CachingConfiguration.java

Fix bug hazelcast

---

src/main/java/de/muenchen/dave/configuration/CachingConfiguration.java

Bugfix Hazelcast

---

.github/workflows/build_push_ghcr.yaml
Dockerfile

* create image in branch sprint
* bump java version

Imagebranchsprint

---

src/main/java/de/muenchen/dave/domain/pdf/components/MessstelleninformationenPdfComponent.java
src/main/java/de/muenchen/dave/services/pdfgenerator/FillPdfBeanService.java
src/main/resources/pdf/templates/messstelle/parts/messstelleninformationen.mustache
src/test/java/de/muenchen/dave/services/pdfgenerator/FillPdfBeanServiceTest.java

Mustach aktualisiert, sodass der Wochentag nur noch angezeigt wird, wenn es sich um einen Zeitraum handelt.

Fix Bug DAVE-355

---

README.md
src/main/java/de/muenchen/dave/services/messstelle/ListenausgabeService.java
src/test/java/de/muenchen/dave/services/messstelle/ListenausgabeServiceTest.java

Bug Hotfix Summenbildung mit letzten Intervall des Tages
Issues:

Bug Hotfix Summenbildung mit letzten Intervall des Tages

---

pom.xml
src/main/java/de/muenchen/dave/configuration/SecurityConfiguration.java
src/main/java/de/muenchen/dave/domain/BaseEntity.java
src/main/resources/application-docker.yml
src/main/resources/application.yml
src/test/java/de/muenchen/dave/domain/dtos/BearbeiteZaehlstelleDTORandomFactory.java
src/test/java/de/muenchen/dave/domain/dtos/BearbeiteZaehlungDTORandomFactory.java
src/test/java/de/muenchen/dave/domain/elasticsearch/ZaehlstelleRandomFactory.java
src/test/java/de/muenchen/dave/domain/elasticsearch/ZaehlungRandomFactory.java
src/test/java/de/muenchen/dave/domain/mapper/StadtbezirkMapperTest.java
src/test/java/de/muenchen/dave/spring/ProcessZaehldatenBelastungsplanServiceSpringTest.java
src/test/java/de/muenchen/dave/spring/ZeitauswahlServiceTest.java
src/test/java/de/muenchen/dave/spring/services/InfoMessageServiceTest.java
src/test/java/de/muenchen/dave/spring/services/SucheServiceSpringTests.java
src/test/java/de/muenchen/dave/spring/services/ZaehlstelleIndexServiceSpringTest.java
src/test/java/de/muenchen/dave/spring/services/auswertung/AuswertungSpitzenstundeServiceSpringTest.java
src/test/java/de/muenchen/dave/spring/services/auswertung/AuswertungZaehlstellenKoordinateServiceTest.java
src/test/java/de/muenchen/dave/spring/services/csvgenerator/GenerateCsvServiceSpringTest.java
src/test/java/de/muenchen/dave/spring/services/ladezaehldaten/LadeZaehldatenServiceSpringTest.java
src/test/java/de/muenchen/dave/spring/services/pdfgenerator/FillPdfBeanServiceSpringTest.java
src/test/java/de/muenchen/dave/spring/services/pdfgenerator/FillZeitreihePdfBeanServiceSpringTest.java
src/test/java/de/muenchen/dave/spring/services/pdfgenerator/GeneratePdfServiceSpringTest.java
src/test/java/de/muenchen/dave/spring/services/pdfgenerator/ReportServiceSpringTest.java
src/test/java/de/muenchen/dave/spring/services/persist/ExternalZaehlungPersistierungsServiceSpringTest.java

- Hebung Spring Boot und Spring Cloud
- Anpassung Properties wegen Deprecation
- Entfernen nicht nötiger Properties wegen Paginierung RestRepoResource
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.4-Release-Notes#upgrading-from-spring-boot-33

Hebung Spring Boot und Spring Cloud

---

src/main/resources/pdf/templates/parts/schematische-uebersicht.mustache

Hotfi für die Schematische Übersicht

Hotfix DAVE-486 Schematische Uebersicht

---

src/main/java/de/muenchen/dave/util/ChartLegendUtil.java
src/test/java/de/muenchen/dave/services/messstelle/GanglinieServiceTest.java
src/test/java/de/muenchen/dave/services/messstelle/auswertung/GanglinieGesamtauswertungServiceTest.java

Labeltexte angepasst
Issues: DAVE-244

Dave 244 uebersichtlichkeit

---

pom.xml
src/main/java/de/muenchen/dave/domain/enums/ZaehldatenIntervall.java

Hebung Spring Framework

---

src/main/resources/pdf/templates/belastungsplan.mustache
src/main/resources/pdf/templates/datentabelle.mustache
src/main/resources/pdf/templates/ganglinie.mustache
src/main/resources/pdf/templates/zeitreihe.mustache

Fix DAVE-512

---

src/main/java/de/muenchen/dave/domain/dtos/laden/LadeZaehldatumDTO.java
src/main/java/de/muenchen/dave/services/processzaehldaten/ProcessZaehldatenZeitreiheService.java

change Methode to calculate gesamt

Fix DAVE-509

---

src/main/java/de/muenchen/dave/services/SucheService.java

add filter to zeitraum suggestion

Fix DAVE-505

---

src/main/java/de/muenchen/dave/controller/LadeZaehldatenController.java
src/main/java/de/muenchen/dave/domain/dtos/laden/LadeProcessedZaehldatenDTO.java
src/main/java/de/muenchen/dave/services/pdfgenerator/FillZeitreihePdfBeanService.java
src/main/java/de/muenchen/dave/services/processzaehldaten/ProcessZaehldatenService.java
src/main/java/de/muenchen/dave/services/processzaehldaten/ProcessZaehldatenZeitreiheService.java

zaehldaten werden nun in einem Request geladen

Fix DAVE-507

---

src/main/java/de/muenchen/dave/services/IndexServiceUtils.java
src/main/java/de/muenchen/dave/services/SucheService.java
src/main/java/de/muenchen/dave/services/ZaehlstelleIndexService.java
src/test/java/de/muenchen/dave/domain/elasticsearch/ZaehlstelleRandomFactory.java
src/test/java/de/muenchen/dave/domain/elasticsearch/ZaehlungRandomFactory.java
src/test/java/de/muenchen/dave/services/ZaehlstelleIndexServiceUtilsTests.java

Fix DAVE-518

---

src/main/java/de/muenchen/dave/services/auswertung/AuswertungSpitzenstundeService.java

Fix DAVE-514

---

src/main/java/de/muenchen/dave/domain/dtos/laden/LadeZaehldatumDTO.java
src/main/java/de/muenchen/dave/services/processzaehldaten/ProcessZaehldatenZeitreiheService.java
src/test/java/de/muenchen/dave/services/processzaehldaten/ProcessZaehldatenZeitreiheTest.java

always return last three active

Fix DAVE-513

---

src/main/java/de/muenchen/dave/configuration/ShedlockConfiguration.java
src/main/java/de/muenchen/dave/domain/Shedlock.java

---
name: Pull request template
about: Create a pull request to contribute to our software
title: ""
labels: ""
assignees: ""
---
Issues:

add dbschema to shedlock

---

src/main/java/de/muenchen/dave/domain/dtos/messstelle/EditMessstelleDTO.java
src/main/java/de/muenchen/dave/domain/mapper/detektor/MessstelleMapper.java
src/test/java/de/muenchen/dave/domain/mapper/MessstelleMapperTests.java

add lageplan-info to DTO used by admin-portal
Issues: dave-124
~ [ ] Documentation is complemented (operator manual, system specification)~
~ [ ] Infrastructure is adjusted~

lageplanVorhanden added

---

src/main/java/de/muenchen/dave/configuration/FlywaySchemaCallback.java

Register the needed Events, dont close reused connection and create schema.
Issues: DAVE-539

fix for schema path + creation

---

.github/workflows/build_push_stable.yaml

fixed branch name in workflow

---

src/main/java/de/muenchen/dave/controller/SucheController.java

---
name: Pull request template
about: Create a pull request to contribute to our software
title: ""
labels: ""
assignees: ""
---
Issues:

Hotfix: Show error message (#271)

---

src/main/java/de/muenchen/dave/services/SucheService.java

* add logging for zaehlung debug
* remove logfile
---
name: Pull request template
about: Create a pull request to contribute to our software
title: ""
labels: ""
assignees: ""
---
Issues:

Add Logging for Zaehlung (#274)

---

src/main/java/de/muenchen/dave/controller/MapConfigController.java
src/main/java/de/muenchen/dave/domain/dtos/init/MapConfigDTO.java
src/main/java/de/muenchen/dave/services/MapConfigService.java
src/main/resources/application.yml

Kartenfokus München ist jetzt konfigurierbar.
Issues: DAVE-563, https://github.com/it-at-m/dave/issues/5

Dave 563 map focus

---

src/main/java/de/muenchen/dave/services/pdfgenerator/FillZeitreihePdfBeanService.java
src/main/java/de/muenchen/dave/services/pdfgenerator/GeneratePdfService.java
src/test/java/de/muenchen/dave/services/pdfgenerator/FillZeitreihePdfBeanServiceTest.java

use default Zeitauswahl creation

Fix DAVE-532

---

src/main/java/de/muenchen/dave/services/MapConfigService.java
src/main/resources/application.yml

fix default zoom

---

src/main/java/de/muenchen/dave/domain/dtos/suche/SucheComplexSuggestsDTO.java

Fix Dave-557

---

pom.xml
src/main/java/de/muenchen/dave/configuration/ShedlockConfiguration.java

Hebung Spring Frameworks
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.5-Release-Notes#upgrading-from-spring-boot-34
https://github.com/spring-cloud/spring-cloud-release/wiki/Spring-Cloud-2025.0-Release-Notes

DAVE-648 Hebung Spring Frameworks

---

src/main/java/de/muenchen/dave/domain/dtos/messstelle/EditMessquerschnittDTO.java
src/main/java/de/muenchen/dave/domain/dtos/messstelle/EditMessstelleDTO.java
src/main/java/de/muenchen/dave/domain/dtos/messstelle/MessstelleTooltipDTO.java
src/main/java/de/muenchen/dave/domain/dtos/messstelle/ReadMessstelleInfoDTO.java
src/main/java/de/muenchen/dave/domain/dtos/messstelle/auswertung/MessstelleAuswertungDTO.java
src/main/java/de/muenchen/dave/domain/elasticsearch/detektor/Messstelle.java
src/main/java/de/muenchen/dave/domain/enums/Verkehrsart.java
src/main/java/de/muenchen/dave/domain/mapper/VerkehrsartMapper.java
src/main/java/de/muenchen/dave/domain/mapper/detektor/MessstelleMapper.java
src/main/java/de/muenchen/dave/domain/mapper/detektor/MessstelleReceiverMapper.java
src/main/java/de/muenchen/dave/services/messstelle/GenerateCsvMstService.java
src/main/java/de/muenchen/dave/services/messstelle/MessstelleService.java
src/main/java/de/muenchen/dave/services/pdfgenerator/FillPdfBeanService.java
src/main/resources/api/geodateneai.json
src/test/java/de/muenchen/dave/domain/elasticsearch/MessstelleRandomFactory.java
src/test/java/de/muenchen/dave/domain/mapper/MessstelleMapperTests.java
src/test/java/de/muenchen/dave/domain/mapper/MessstelleReceiverMapperTests.java
src/test/java/de/muenchen/dave/domain/mapper/SucheMapperTests.java
src/test/java/de/muenchen/dave/services/csvgenerator/GenerateCsvMstServiceTest.java
src/test/java/de/muenchen/dave/services/messstelle/BelastungsplanServiceTest.java
src/test/java/de/muenchen/dave/services/messstelle/MessstelleReceiverTest.java
src/test/java/de/muenchen/dave/services/pdfgenerator/FillPdfBeanServiceTest.java

detektierte Verkehrsart als enum uebermitteln und verarbeiten

Refactor Verkehrsart as Enum
